#!/bin/bash

conda create --name micscriptlib python=3.11
conda activate micscriptlib
mamba install \
    pip \
    scipy \
    numpy \
    pillow \
    nibabel \
    pandas \
    pybids \
    pyqt \
    pyqt5-sip \
    "pyqtgraph<0.13"
